import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    SVM_RPC_HTTP_DEVNET: z.string(),  
    SVM_RPC_HTTP_MAINNET: z.string(),
    EVM_RPC_HTTP_1: z.string(),
    EVM_RPC_HTTP_10: z.string(),
    EVM_RPC_HTTP_56: z.string(),
    EVM_RPC_HTTP_130: z.string(),
    EVM_RPC_HTTP_137: z.string(),
    EVM_RPC_HTTP_250: z.string(),
    EVM_RPC_HTTP_369: z.string(),
    EVM_RPC_HTTP_1284: z.string(),
    EVM_RPC_HTTP_1285: z.string(),
    EVM_RPC_HTTP_8453: z.string(),
    EVM_RPC_HTTP_9001: z.string(),
    EVM_RPC_HTTP_17000: z.string(),
    EVM_RPC_HTTP_42161: z.string(),
    EVM_RPC_HTTP_43114: z.string(),
    EVM_RPC_HTTP_11155111: z.string(),
  },
  client: {
    // NEXT_PUBLIC_CLIENTVAR: z.string(),
  },
  runtimeEnv: {
    SVM_RPC_HTTP_DEVNET: process.env.SVM_RPC_HTTP_DEVNET,
    SVM_RPC_HTTP_MAINNET: process.env.SVM_RPC_HTTP_MAINNET,
    EVM_RPC_HTTP_1: process.env.EVM_RPC_HTTP_1,
    EVM_RPC_HTTP_10: process.env.EVM_RPC_HTTP_10,
    EVM_RPC_HTTP_56: process.env.EVM_RPC_HTTP_56,
    EVM_RPC_HTTP_130: process.env.EVM_RPC_HTTP_130,
    EVM_RPC_HTTP_137: process.env.EVM_RPC_HTTP_137,
    EVM_RPC_HTTP_250: process.env.EVM_RPC_HTTP_250,
    EVM_RPC_HTTP_369: process.env.EVM_RPC_HTTP_369,
    EVM_RPC_HTTP_1284: process.env.EVM_RPC_HTTP_1284,
    EVM_RPC_HTTP_1285: process.env.EVM_RPC_HTTP_1285,
    EVM_RPC_HTTP_8453: process.env.EVM_RPC_HTTP_8453,
    EVM_RPC_HTTP_9001: process.env.EVM_RPC_HTTP_9001,
    EVM_RPC_HTTP_17000: process.env.EVM_RPC_HTTP_17000,
    EVM_RPC_HTTP_42161: process.env.EVM_RPC_HTTP_42161,
    EVM_RPC_HTTP_43114: process.env.EVM_RPC_HTTP_43114,
    EVM_RPC_HTTP_11155111: process.env.EVM_RPC_HTTP_11155111,
  },
});