name: Deploy to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SVM_RPC_HTTP_MAINNET: ${{ secrets.SVM_RPC_HTTP_MAINNET }}
      EVM_RPC_HTTP_1: ${{ secrets.EVM_RPC_HTTP_1 }}
      EVM_RPC_HTTP_137: ${{ secrets.EVM_RPC_HTTP_137 }}
      EVM_RPC_HTTP_369: ${{ secrets.EVM_RPC_HTTP_369 }}
      EVM_RPC_HTTP_8453: ${{ secrets.EVM_RPC_HTTP_8453 }}
      EVM_RPC_HTTP_17000: ${{ secrets.EVM_RPC_HTTP_17000 }}
      EVM_RPC_HTTP_11155111: ${{ secrets.EVM_RPC_HTTP_11155111 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies and tools
        id: cache-all
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /usr/bin/convert
            /usr/bin/inkscape
            /usr/bin/rclone
          key: ${{ runner.os }}-deps-tools-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-deps-tools-

      - name: Install dependencies
        if: steps.cache-all.outputs.cache-hit != 'true'
        run: bun install

      - name: Install ImageMagick
        if: steps.cache-all.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          
      - name: Install Inkscape
        if: steps.cache-all.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Install rclone
        if: steps.cache-all.outputs.cache-hit != 'true'
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for Cloudflare R2
        run: |
          rclone config create r2ocfs s3 \
            provider Cloudflare \
            access_key_id ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }} \
            secret_access_key ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }} \
            endpoint ${{ secrets.CLOUDFLARE_R2_ENDPOINT }} \
            acl private

      - name: Build dist/ with Bun
        run: bun run deploy

      - name: Deploy to Cloudflare R2
        run: rclone copy dist/ r2ocfs:ocfs
