name: Deploy to Cloudflare R2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RPC_HTTP_1: ${{ secrets.RPC_HTTP_1 }}
      RPC_HTTP_369: ${{ secrets.RPC_HTTP_369 }}
      RPC_HTTP_8453: ${{ secrets.RPC_HTTP_8453 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for Cloudflare R2
        run: |
          rclone config create r2ocfs s3 \
            provider Cloudflare \
            access_key_id ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }} \
            secret_access_key ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }} \
            endpoint ${{ secrets.CLOUDFLARE_R2_ENDPOINT }} \
            acl private

      - name: Build dist/ with Bun
        run: bun deploy

      - name: Deploy to Cloudflare R2
        run: rclone copy dist/ r2ocfs:ocfs
